version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - "Pr0Ger"

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  allow:
  - dependency-type: "direct"
  reviewers:
  - "Pr0Ger"
