version: "2"

linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck
  - cyclop
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - err113
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forcetypeassert
  - funcorder
  - funlen
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gomoddirectives
  - goprintffuncname
  - gosec
  - gosmopolitan
  - iface
  - lll
  - loggercheck
  - maintidx
  - makezero
  - misspell
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnesserr
  - noctx
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - spancheck
  - sqlclosecheck
  - staticcheck
  - tagliatelle
  - testifylint
  - thelper
  - tparallel
  - unconvert
  - unparam
  - usestdlibvars
  - usetesting
  - wastedassign
  - whitespace
  - wrapcheck
  - zerologlint
  settings:
    dogsled:
      max-blank-identifiers: 3
    errcheck:
      exclude-functions:
      - (net/http.ResponseWriter).Write
      - github.com/go-chi/render.Render
      - github.com/go-chi/render.RenderList
    errorlint:
      errorf: true
    funlen:
      lines: 100
      statements: 60
    godot:
      scope: declarations
    gomoddirectives:
      replace-local: true
      retract-allow-no-explanation: false
    iface:
      enable:
      - identical
      - unused
    lll:
      tab-width: 4
    rowserrcheck:
      packages:
      - github.com/jmoiron/sqlx
    tagalign:
      sort: false
    tagliatelle:
      case:
        rules:
          json: goSnake
          yaml: goSnake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - linters:
      - dupl
      - err113
      - forcetypeassert
      path: _test\.go
    - linters:
      - gosec
      text: weak random number generator
    paths:
    - third_party$
    - builtin$
    - examples$

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(go.pr0ger.dev/x)
    goimports:
      local-prefixes:
      - go.pr0ger.dev/x
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
