name: tests
on:
  push:
    branches:
    - master
  pull_request:
  workflow_run:
    workflows: [lint]
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: stable
    - name: Install mockgen
      run: go install go.uber.org/mock/mockgen@latest
    - name: Generate mocks
      run: go generate -x ./...
    - name: Run tests
      run: go test -v ./...
